- id: '1695170301853'
  alias: Shopping List Reminder
  description: ''
  trigger:
  - platform: state
    entity_id: person.sammy_hillzere
    from: not_home
    to: shopping
    for:
      minutes: 3
  - platform: state
    entity_id: person.sammy_hillzere
    from: not_home
    to: shopping_2
    for:
      minutes: 3
  - platform: state
    entity_id: person.sammy_hillzere
    from: not_home
    to: shopping_3
    for:
      minutes: 3
  - platform: state
    entity_id: person.sammy_hillzere
    from: not_home
    to: shopping_4
    for:
      minutes: 3
  - platform: state
    entity_id: person.sammy_hillzere
    from: not_home
    to: shopping_5
    for:
      minutes: 3
  - platform: state
    entity_id: person.sammy_hillzere
    from: not_home
    to: shopping_7
    for:
      minutes: 3
  - platform: state
    entity_id: person.thomas_hillzere
    from: not_home
    to: shopping
    for:
      minutes: 3
  - platform: state
    entity_id: person.thomas_hillzere
    from: not_home
    to: shopping_2
    for:
      minutes: 3
  - platform: state
    entity_id: person.thomas_hillzere
    from: not_home
    to: shopping_3
    for:
      minutes: 3
  - platform: state
    entity_id: person.thomas_hillzere
    from: not_home
    to: shopping_4
    for:
      minutes: 3
  - platform: state
    entity_id: person.thomas_hillzere
    from: not_home
    to: shopping_5
    for:
      minutes: 3
  - platform: state
    entity_id: person.thomas_hillzere
    from: not_home
    to: shopping_7
    for:
      minutes: 3
  action:
  - service: notify.phones
    data:
      message: Would you like to open your shopping list?
      data:
        clickAction: /dashboard-mushroom/shopping-list
        url: /dashboard-mushroom/shopping-list
  mode: single
- id: '1695353672098'
  alias: Lock Car
  description: ''
  trigger:
  - platform: state
    entity_id:
    - lock.2021_cx_30_2_5_s_pf_awd_lock
    to: unlocked
    from:
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.2021_cx_30_2_5_s_pf_awd_lock
  mode: single
- id: '1695532602218'
  alias: Backup Home Assistant every night at 3 AM
  description: ''
  trigger:
    platform: time
    at: 03:00:00
  action:
    alias: Create backup now
    service: backup.create
- id: '1695618046786'
  alias: Flash lights when pearl leaves
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.pearl_tracker
    - person.pearl
    to: not_home
    for:
      hours: 0
      minutes: 0
      seconds: 30
    from:
  condition: []
  action:
  - service: light.turn_on
    data:
      color_name: red
    target:
      area_id:
      - bedroom
      - dining_room
      - kitchen
      - living_room
      - office
  mode: single
- id: '1695678861300'
  alias: Turn on Office Lights when Thomas in office
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.thomas_s_apple_watch
    to: office
    for:
      hours: 0
      minutes: 3
      seconds: 0
    from:
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      device_id:
      - a1fe2fa603e5abc155131f0988897055
      - d8a66aaaceeee3b3e22d002da328d5e9
  mode: single
- id: '1695690186251'
  alias: Turn on bedside lamps when Thomas goes in
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.thomas_s_apple_watch
    to: bedroom
    for:
      hours: 0
      minutes: 0
      seconds: 0
    from:
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 40
    target:
      device_id: 09c18196b5b157f9dc4ce3b2902e7779
  mode: single
- id: '1697407831421'
  alias: Pearl Watch
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.pearl
    from: backyard
    for:
      hours: 0
      minutes: 0
      seconds: 20
    to: not_home
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.pearl_watch_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
      state: 'on'
  action:
  - service: script.1696880284623
    data:
      persistant: false
      email: false
      mobile: true
      emergency: true
      notify_alexa: false
      notify_google_home: true
      log: false
      message: Pearl has escaped!
      entities:
        entity_id:
        - media_player.dining_room_speaker
        - media_player.kitchen_display
  mode: single
- id: '1697826912190'
  alias: button to turn Pearl Watch on
  description: ''
  trigger:
  - device_id: 202d73f1233fa556fb983bf26b5b7409
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button
  condition: []
  action:
  - service: input_boolean.toggle
    data: {}
    target:
      entity_id: input_boolean.pearl_watch_on
  mode: single
- id: '1697827163891'
  alias: Basement Door Open turns on Pearl Watch
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.pearl_watch_on
  mode: single
- id: '1697827522422'
  alias: Notify Pearl Watch On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.pearl_watch_on
    from: 'off'
    to: 'on'
    id: to_on
  - platform: state
    entity_id:
    - input_boolean.pearl_watch_on
    from: 'on'
    to: 'off'
    id: to_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - to_on
      sequence:
      - service: script.1696880284623
        data:
          persistant: false
          email: false
          mobile: true
          emergency: false
          notify_alexa: false
          notify_google_home: true
          log: false
          message: Pearl Watch On!
          entities:
            entity_id:
            - media_player.dining_room_speaker
            - media_player.kitchen_display
    - conditions:
      - condition: trigger
        id:
        - to_off
      sequence:
      - service: script.1696880284623
        data:
          persistant: false
          email: false
          mobile: true
          emergency: false
          notify_alexa: false
          notify_google_home: true
          log: false
          message: Pearl Watch Off!
          entities:
            entity_id:
            - media_player.dining_room_speaker
            - media_player.kitchen_display
  mode: single
- id: '1697998501943'
  alias: Turn off HVAC when door or windows are open
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.house_sealed
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 3
      seconds: 0
    id: Open
  - platform: state
    entity_id:
    - binary_sensor.house_sealed
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: Closed
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Open
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: 'off'
        target:
          entity_id: climate.main_unit
    - conditions:
      - condition: trigger
        id:
        - Closed
      - condition: not
        conditions:
        - condition: state
          entity_id: climate.main_unit
          state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat_cool
        target:
          entity_id: climate.main_unit
  mode: single
- id: '1700082051818'
  alias: All office lights act as one switch
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.office_dimmer_light
    from: 'on'
    id: 'On'
  - platform: state
    entity_id:
    - light.office_dimmer_light
    from: 'off'
    id: 'Off'
  condition:
  - condition: time
    after: 08:00:00
    before: '19:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - if:
    - condition: trigger
      id:
      - 'On'
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.all_office_lights
    else:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.all_office_lights
  mode: single
- id: '1700980232130'
  alias: Update Cat Litter Counter
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_vibration_aq1_vibration
    - binary_sensor.vibration_two_vibration_2
    to: 'on'
    from: 'off'
    id: pooped
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_vibration_aq1_vibration
    - binary_sensor.vibration_two_vibration_2
    to: 'on'
    from: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: scooped
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - pooped
      sequence:
      - service: counter.increment
        data: {}
        target:
          entity_id: counter.cat_litter_counter
    - conditions:
      - condition: trigger
        id:
        - scooped
      sequence:
      - service: counter.reset
        data: {}
        target:
          entity_id: counter.cat_litter_counter
      - service: input_select.select_option
        data:
          option: Clean
        target:
          entity_id: input_select.litter_status
  mode: single
- id: '1700980376992'
  alias: Notify Scoop Cat Litter
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - counter.cat_litter_counter
    above: 5
  condition: []
  action:
  - service: notify.phones
    data:
      message: Scoop Cat Litter
  - service: input_select.select_option
    data:
      option: Needs Scooping
    target:
      entity_id: input_select.litter_status
  mode: single
- id: '1708205264830'
  alias: Low Battery Notifications & Actions
  description: ''
  use_blueprint:
    path: Blackshome/low-battery-notifications-and-actions.yaml
    input:
      include_time: time_enabled
      time: '17:00:00'
      weekday_options:
      - sun
      exclude_sensors:
        entity_id:
        - sensor.iphone_battery_level
        - sensor.sammy_ozeres_iphone_battery_level
        - sensor.roborock_q7_max_battery
      notify_device:
      - 1f1ec731bdae5cbaccb7b94a7eccb659
      include_easy_notify: enable_easy_notify
- id: '1713654864639'
  alias: Turn on bedside lamps at night
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-30'
  condition:
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.sammy_hillzere
      zone: zone.home
    - condition: zone
      entity_id: person.thomas_hillzere
      zone: zone.home
  action:
  - type: turn_on
    device_id: 44a8e7936f830f6d0039db68b7ff36e3
    entity_id: db01e91da6a82110279b1ecc55536f4c
    domain: light
    brightness_pct: 55
  - type: turn_on
    device_id: 96a097cab3b948ba8f9e537a658df3a0
    entity_id: 97a29104142dd340a6ae62a38b3d3168
    domain: light
    brightness_pct: 55
  mode: single
- id: '1718082107100'
  alias: speak
  description: ''
  trigger: []
  condition: []
  action:
  - service: script.1696880284623
    metadata: {}
    data:
      persistant: false
      email: false
      mobile: true
      emergency: true
      notify_alexa: false
      notify_google_home: true
      log: false
      message: 'What is fresh pasta '
      entities:
        device_id:
        - 3369a38281f17feda957b655753a0c0d
        - d34774d32757bba7474d23786a467ec3
        - 4f70d65b9350c73cf03c3d3fd8a9987d
  mode: single
- id: '1722319978153'
  alias: Bedroom Air Purifier
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
    id: Evening
  - platform: time
    at: 07:00:00
    id: Early_morning
  - platform: time
    at: 09:00:00
    id: Morning
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Evening
      sequence:
      - service: fan.set_preset_mode
        metadata: {}
        data:
          preset_mode: sleep
        target:
          entity_id: fan.bedroom_airy
    - conditions:
      - condition: trigger
        id:
        - Morning
      sequence:
      - service: fan.set_percentage
        metadata: {}
        data:
          percentage: 66
        target:
          entity_id: fan.bedroom_airy
    - conditions:
      - condition: trigger
        id:
        - Early_morning
      sequence:
      - service: fan.set_percentage
        metadata: {}
        data:
          percentage: 33
        target:
          entity_id: fan.bedroom_airy
  mode: single
- id: '1722320281817'
  alias: Keep HVAC off if house is unsealed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - climate.main_unit
    from: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.house_sealed
    state: 'on'
  action:
  - service: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: 'off'
    target:
      device_id: a0bb2fd76b12ab3d3ab2cfd1d0c256dc
  mode: single
