# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - name: Phones
    platform: group
    services:
    - service: mobile_app_thomas_iphone
    - service: mobile_app_sammy_ozeres_iphone

sensor: !include sensors.yaml

logger:
  default: info
  logs:
    custom_components.hacs: debug
    aiogithubapi: debug
    custom_components.kumo: debug
    custom_components.scrypted: debug

http:
#  ssl_certificate: /config/letsencrypt/live/hillzere.com/fullchain.pem
#  ssl_key: /config/letsencrypt/live/hillzere.com/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.10.1
    - 10.0.1.1
    - 10.0.10.3

google_assistant:
  project_id: inspired-gear-368219
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
  
device_tracker:
  - platform: bluetooth_le_tracker

# webhook should be working now
