# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - name: Phones
    platform: group
    services:
    - service: mobile_app_thomas_iphone
    - service: mobile_app_sammy_ozeres_iphone

sensor: !include sensors.yaml

logger:
  default: info
  logs:
    custom_components.hacs: debug
    aiogithubapi: debug
    custom_components.kumo: debug
    custom_components.scrypted: debug

http:
  ssl_certificate: /config/letsencrypt/live/hillzere.com/fullchain.pem
  ssl_key: /config/letsencrypt/live/hillzere.com/privkey.pem

google_assistant:
  project_id: inspired-gear-368219
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
  
device_tracker:
  - platform: bluetooth_le_tracker

panel_iframe:
  portainer:
    title: "Portainer"
    url: "https://home.hillzere.com:9443/#!/2/docker/containers"
    icon: mdi:docker
    require_admin: true
  configurator:
    title: "Configurator"
    url: "https://config.hillzere.com"
    icon: mdi:cog
    require_admin: true

# webhook should be working now
